# Generated by Django 5.0.6 on 2024-06-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='logo',
            field=models.ImageField(default='path/to/default_logo.png', upload_to='language_logos/'),
        ),
    ]
