# Generated by Django 5.0.6 on 2024-06-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_me', '0002_programminglanguage_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
