# Generated by Django 5.0.6 on 2024-06-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_me', '0003_aboutme_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
